services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prx-backend-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: prx-backend-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
